# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: astral

before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/astral/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"
# nfpms:
#   - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
#     homepage: https://github.com/sj14/astral/
#     description: Calculations for the position of the sun and moon.
#     license: Apache License 2.0
#     formats:
#       - deb
#       - rpm
#       - apk # not tested
#     builds:
#       - astral
brews:
  - name: astral
    skip_upload: auto
    repository:
      owner: sj14
      name: homebrew-tap
    description: Calculations for the position of the sun and moon.
release:
  github:
    owner: sj14
    name: astral
  disable: false
  draft: false
  prerelease: auto
changelog:
  filters:
    exclude:
      - typo
