# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: astral

before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/astral/main.go
    id: "astral"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - dragonfly
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - id: astral
    builds:
    - astral
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - AUTHORS
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"
nfpms:
  - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
    homepage: https://github.com/sj14/astral/
    description: Calculations for the position of the sun and moon.
    license: Apache License 2.0
    formats:
      - deb
      - rpm
    builds:
      - astral
brews:
  - name: astral
    ids:
      - astral
    tap:
      owner: sj14
      name: homebrew-tap
    description: Calculations for the position of the sun and moon.
release:
  github:
    owner: sj14
    name: astral
  disable: false
  draft: false
  prerelease: false
changelog:
  filters:
    exclude:
      - typo
